tuned-gui: Sort plugins based on their name
Previously the sorting was done by comparing the objects themselves,
which is not what we want and it doesn't work in Python 3 - TypeError
is raised, e.g:
TypeError: '<' not supported between instances of 'BootloaderPlugin' and 'MountsPlugin'

Signed-off-by: Ondřej Lysoněk <olysonek@redhat.com>